services:
  - type: web
    name: synaptic-sound-api
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SPOTIFY_CLIENT_ID
        sync: false
      - key: SPOTIFY_CLIENT_SECRET
        sync: false
      - key: SPOTIFY_REDIRECT_URI
        value: https://synaptic-sound.com/callback
      - key: ENCRYPTION_KEY
        sync: false
      - key: SESSION_SECRET
        sync: false
      - key: COOKIE_DOMAIN
        value: synaptic-sound.com